Pandas Test1

In [2]:
import pandas as pd
import numpy as np

Series

In [3]:
mydata = ['Boat','Car','Bike','Truck']

myseries1 = pd.Series(mydata)

In [4]:
print(myseries1)

0     Boat
1      Car
2     Bike
3    Truck
dtype: object

In [5]:
mydata = [1, 55, 99, 43]

myseries2 = pd.Series(mydata)

In [6]:
print(myseries2)

0     1
1    55
2    99
3    43
dtype: int64

## Data Frame

In [7]:
mydfdata = [('Boat', 1), ('Car', 55), ('Bike', 99), ('Truck', 43)]

mydf = pd.DataFrame(mydfdata)

In [8]:
mydf

       0   1
0   Boat   1
1    Car  55
2   Bike  99
3  Truck  43

In [9]:
mydf = pd.DataFrame(mydfdata, columns=['Thing', 'count'])

mydf

   Thing  count
0   Boat      1
1    Car     55
2   Bike     99
3  Truck     43

In [10]:
mydf['count']

0     1
1    55
2    99
3    43
Name: count, dtype: int64

In [11]:
type(mydf['Thing'])

pandas.core.series.Series

In [12]:
print(mydfdata)

[('Boat', 1), ('Car', 55), ('Bike', 99), ('Truck', 43)]

In [13]:
mydf.dtypes

Thing    object
count     int64
dtype: object

## Reading in data

In [14]:
df = pd.read_csv('../input/mr-beast-youtube-video-statistics/MrBeast_youtube_stats.csv')

In [15]:
#inspect the data

In [16]:
#Head / Tail
df.head()

,id,title,description,publishTime,kind_stats,duration_seconds,viewCount,likeCount,commentCount,thumbnails.default.url,...,thumbnails.high.width,thumbnails.high.height,contentDetails.duration,contentDetails.dimension,topicDetails.topicCategories,snippet.defaultLanguage,localizations.en.title,localizations.en.description,snippet.tags,contentDetails.contentRating.ytRating
0,TQHEJj68Jew,I Got Hunted By A Real Bounty Hunter,"Sign up for Current w/ my Creator Code ""BEAST""...",2021-04-24 20:00:00+00:00,youtube#video,861,84717282.0,2876493.0,128922.0,https://i.ytimg.com/vi/TQHEJj68Jew/default.jpg,...,480.0,360.0,PT14M21S,2d,['https://en.wikipedia.org/wiki/Lifestyle_(soc...,NaN,NaN,NaN,NaN,NaN
1,00NgUctWoLQ,"Extreme $1,000,000 Hide And Seek",I didn't expect that to happen at the end I wa...,2021-12-18 21:00:00+00:00,youtube#video,729,32090178.0,2125183.0,73593.0,https://i.ytimg.com/vi/00NgUctWoLQ/default.jpg,...,480.0,360.0,PT12M9S,2d,['https://en.wikipedia.org/wiki/Lifestyle_(soc...,en,"Extreme $1,000,000 Hide And Seek",I didn't expect that to happen at the end I wa...,NaN,NaN
2,NaN,MrBeast,Accomplishments - Raised $20000000 To Plant 20...,2012-02-20 00:43:50+00:00,NaN,0,NaN,NaN,NaN,https://yt3.ggpht.com/ytc/AKedOLTctGKJ32CdDLiS...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ayXxwJJId_c,I Bought The World&#39;s Largest Mystery Box! ...,I cant believe I spent over $500000 on mystery...,2021-04-03 20:00:01+00:00,youtube#video,709,101745632.0,3110824.0,162796.0,https://i.ytimg.com/vi/ayXxwJJId_c/default.jpg,...,480.0,360.0,PT11M49S,2d,['https://en.wikipedia.org/wiki/Lifestyle_(soc...,NaN,NaN,NaN,NaN,NaN
4,cExLQ1o2pDw,"First To Rob Bank Wins $100,000",I didnt think he would actually rob the bank.....,2021-09-26 20:00:06+00:00,youtube#video,482,50008942.0,2359606.0,120621.0,https://i.ytimg.com/vi/cExLQ1o2pDw/default.jpg,...,480.0,360.0,PT8M2S,2d,['https://en.wikipedia.org/wiki/Lifestyle_(soc...,NaN,NaN,NaN,NaN,NaN

In [17]:
df.tail()

,id,title,description,publishTime,kind_stats,duration_seconds,viewCount,likeCount,commentCount,thumbnails.default.url,...,thumbnails.high.width,thumbnails.high.height,contentDetails.duration,contentDetails.dimension,topicDetails.topicCategories,snippet.defaultLanguage,localizations.en.title,localizations.en.description,snippet.tags,contentDetails.contentRating.ytRating
242,yeHjsYQ076A,Remember When COD Was Fun?,"Yup, another very pointless video ▻ Subscribe?...",2015-04-26 21:26:36+00:00,youtube#video,216,16312.0,574.0,145.0,https://i.ytimg.com/vi/yeHjsYQ076A/default.jpg,...,480.0,360.0,PT3M36S,2d,['https://en.wikipedia.org/wiki/Action-adventu...,NaN,NaN,NaN,"['How', 'much', 'money', 'does', 'make', 'blac...",NaN
243,X7doE4h6W64,Insane Gun Sync - 7 Hours To Make,Look at this - http://gyazo.com/8852509d2350db...,2015-06-21 12:22:34+00:00,youtube#video,134,15740.0,637.0,105.0,https://i.ytimg.com/vi/X7doE4h6W64/default.jpg,...,480.0,360.0,PT2M14S,2d,['https://en.wikipedia.org/wiki/Action-adventu...,NaN,NaN,NaN,"['How', 'much', 'money', 'does', 'make', 'blac...",NaN
244,AIytwdufwW8,MY MESSAGE TO COD YOUTUBERS (Watch till end plz),The beginning of the video is a little off top...,2015-05-29 20:07:48+00:00,youtube#video,292,18502.0,508.0,117.0,https://i.ytimg.com/vi/AIytwdufwW8/default.jpg,...,480.0,360.0,PT4M52S,2d,['https://en.wikipedia.org/wiki/Action-adventu...,NaN,NaN,NaN,"['How', 'much', 'money', 'does', 'make', 'blac...",NaN
245,56OkH6ocYZU,L0114R - Biblical Creeper Post for Post @L0114R,His channel - https://www.youtube.com/user/the...,2015-05-15 16:48:54+00:00,youtube#video,109,16627.0,430.0,134.0,https://i.ytimg.com/vi/56OkH6ocYZU/default.jpg,...,480.0,360.0,PT1M49S,2d,['https://en.wikipedia.org/wiki/Action-adventu...,NaN,NaN,NaN,"['How', 'much', 'money', 'does', 'make', 'blac...",NaN
246,zi7tZ-2PhLk,How Much Money Do You Make As An Uber Driver??...,In this video I talk about being an uber drive...,2015-05-31 18:31:25+00:00,youtube#video,304,18773.0,370.0,59.0,https://i.ytimg.com/vi/zi7tZ-2PhLk/default.jpg,...,480.0,360.0,PT5M4S,2d,['https://en.wikipedia.org/wiki/Action-adventu...,NaN,NaN,NaN,"['How', 'much', 'money', 'does', 'make', 'blac...",NaN